// Inlines Alpine.js, the app, and its styles into the single-file UI embedded
// by the gnosis binary from ui/ui.html (see embed.go).
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const [template, styles, alpine, app] = await Promise.all([
  readFile(join(root, "src/index.html"), "utf8"),
  readFile(join(root, "src/styles.css"), "utf8"),
  readFile(join(root, "node_modules/alpinejs/dist/cdn.min.js"), "utf8"),
  readFile(join(root, "src/main.js"), "utf8"),
]);

// Keep the inline script intact even if a dependency ever ships the closing
// tag sequence inside a string literal.
const script = `${alpine}\n${app}`.replace(/<\/script/gi, "<\\/script");

for (const marker of ["<!-- build:style -->", "<!-- build:script -->"]) {
  if (!template.includes(marker)) {
    throw new Error(`src/index.html is missing ${marker}`);
  }
}
const html = template
	.replace("<!-- build:style -->", () => `<style>\n${styles}</style>`)
  .replace("<!-- build:script -->", () => `<script>\n${script}</script>`);

const banner = "<!-- Generated by ui/build.mjs — edit ui/src/* and rebuild with: mise run ui -->\n";
await writeFile(join(root, "ui.html"), banner + html);
console.log("built ui/ui.html");
