// Bundles src/main.js (Alpine.js + app code) and src/styles.css, then inlines
// both into src/index.html to produce the single-file UI embedded by the
// gnosis binary from ui/ui.html (see embed.go).
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));

const result = await build({
  entryPoints: [join(root, "src/main.js")],
  bundle: true,
  minify: true,
  write: false,
  outdir: "out",
  target: "es2020",
  logLevel: "warning",
});

const javascript = result.outputFiles.find((file) => file.path.endsWith(".js"));
const styles = result.outputFiles.find((file) => file.path.endsWith(".css"));
if (!javascript || !styles) {
  throw new Error("esbuild did not produce the expected JS and CSS bundles");
}

// Keep the inline script intact even if a dependency ever ships the closing
// tag sequence inside a string literal.
const script = javascript.text.replace(/<\/script/gi, "<\\/script");

const template = await readFile(join(root, "src/index.html"), "utf8");
for (const marker of ["<!-- build:style -->", "<!-- build:script -->"]) {
  if (!template.includes(marker)) {
    throw new Error(`src/index.html is missing ${marker}`);
  }
}
const html = template
  .replace("<!-- build:style -->", () => `<style>\n${styles.text}</style>`)
  .replace("<!-- build:script -->", () => `<script>\n${script}</script>`);

const banner = "<!-- Generated by ui/build.mjs — edit ui/src/* and rebuild with: mise run ui -->\n";
await writeFile(join(root, "ui.html"), banner + html);
console.log("built ui/ui.html");
