// Package ui bundles the built document UI served by "gnosis serve http".
// ui.html is generated by ui/build.mjs from ui/src and committed so the
// binary builds without Node; rebuild it with "mise run ui".
package ui

import _ "embed"

// HTML is the single-file document UI: markup, styles, and the Alpine.js
// application inlined by the build.
//
//go:embed ui.html
var HTML []byte
